const mongoose = require('mongoose');

const eventSchema = new mongoose.Schema({
    id: {
        type: String,
        required: true
    }, // Can be replace by the by default id generated by mongoDB.
    title: {
        type: String,
        required: true
    },
    description: {
        type: String,
        required: true
    },
    startDate: {
        type: String,
        required: true
    },
    endDate: {
        type: String,
        required: true
    },
    location: {
        longitude: {
            type: Number,
            required: true,
        },
        latitude: {
            type: Number,
            required: true,
        },
    },
    createdBy: {
        type: String,
        required: true,
    },
    createdAt: {
        type: String,
        required: true,
        default: Date.now()
    },
    updatedAt: {
        type: String,
        required: true,
        default: Date.now()

    },

});

export const eventModel = mongoose.model('event', eventSchema);