const mongoose=require('mongoose');

const formSchema=new mongoose.Schema({
    id:{
        type:String,
        required:true
    }, // Can be replace by the by default id generated by mongoDB.

    eventId:{
        type:mongoose.Types.ObjectId,
        ref:'eventModel',
        required:true
    },
    formSchema:{
        type:mongoose.Types.ObjectId,
        ref:'formSchemaModel',
        required:true
    },
    createdAt:{
        type:String,
        required:true,
        default:Date.now()
    },
    updatedAt:{
        type:String,
        required:true,
        default:Date.now()

    },
   
});

export const formModel=mongoose.model('Form',formSchema);