const mongoose = require('mongoose');

const userSchema = new mongoose.Schema({
    id: {
        type: String,
        required: true
    }, // Can be replace by the by default id generated by mongoDB.
    username: {
        type: String,
        required: true
    },
    email: {
        type: String,
        required: true
    },
    password: {
        type: String,
        required: true
    },
    fullName: {
        type: String,
        required: true
    },
    role: {
        type: String,
        enum: ['admin', 'user', 'team'],
        required: true
    },
    createdAt: {
        type: String,
        required: true,
        default: Date.now()
    },
    updatedAt: {
        type: String,
        required: true,
        default: Date.now()

    },
    feedback: [{
        type: String,
    }
    ]

});

export const userModel = mongoose.model('User', userSchema);